Update
Iziwork/consent-manager pull request #230
Opened 2020-08-26 15:00 UTC by julienlucas

2020-08-27 12:18 UTC, AlbinIzi requested changes
Il s'agit d'un composant partagé qui n'est donc pas utilisé uniquement par le site public. La logique ne peut pas reposer sur location, il faut une propriété sur le composant, pas le choix.

2020-08-28 15:05 UTC, julienlucas commented
J'ai ajouté une prop Lang, qu'il faudra donc ajouter aussi sur le composant du plugin du le 2ème site.
En dev mode tout fonctionnait. À tester sur site live.

2020-09-23 08:52 UTC, AlbinIzi requested changes
shouldReload ne devrait pas changer
j'ai testé sur le site pro sans les 2 derniers commit et j'ai la bannière qui reste tout le temps visible même après un refresh et acceptation des cookies.

2020-09-23 14:33 UTC, julienlucas commented
effectivement, oubli de ma part, ça ne ferme pas la popup quand on clique sur OK.
c'est corrigé. j'ai remis shouldReload sur true aussi. en faite je crois que ça ne cause plus le pb de massreload.

faut mettre le bon <script> sur le 2ème site par contre :

`!function () {
 const analytics = window.analytics = window.analytics || []; if (!analytics.initialize) if (analytics.invoked) window.console && console.error && console.error("Segment snippet included twice."); else {
  analytics.invoked = !0; analytics.methods = ["initialize", "trackSubmit", "trackClick", "trackLink", "trackForm", "pageview", "identify", "reset", "group", "track", "ready", "alias", "debug", "page", "once", "off", "on"];
  analytics.factory = function (t) { return function () { var e = Array.prototype.slice.call(arguments); e.unshift(t); analytics.push(e); return analytics } }; for (var t = 0; t < analytics.methods.length; t++) { var e = analytics.methods[t]; analytics[e] = analytics.factory(e) }
 }
}();
analytics.load = function (t, e) {
var n = document.createElement("script"); n.type = "text/javascript"; n.async = !0; n.src = "https://cdn.segment.com/analytics.js/v1/" + t + "/analytics.min.js";
var a = document.getElementsByTagName("script")[0]; a.parentNode.insertBefore(n, a); analytics._loadOptions = e }; analytics.SNIPPET_VERSION = "4.1.0";
analytics.page();`

2020-10-02 13:36 UTC, merged